name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: '0000'
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
        options: >-
          --health-cmd "sqlcmd -S localhost -U SA -P 0000 -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run database migrations
      run: |
        docker run --rm \
          --network host \
          -e "ConnectionStrings__DefaultConnection=Server=localhost;Database=TrafficDb;User=default;Password=0000;" \
          your-docker-image-name \
          dotnet ef database update

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost;Database=TEST;User=default;Password=0000;"
